# Generated by Django 5.2.7 on 2025-11-03 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название склада')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('capacity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вместимость (м³)')),
                ('current_load', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Текущая загрузка (м³)')),
                ('specialization', models.TextField(blank=True, verbose_name='Специализация')),
                ('working_hours', models.TextField(blank=True, verbose_name='Режим работы')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouses', to=settings.AUTH_USER_MODEL, verbose_name='Ответственное лицо')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
            },
        ),
    ]
