# Generated by Django 5.2.7 on 2025-11-03 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='contact_person',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['LOGISTICS_MANAGER', 'DISPATCHER']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouses', to=settings.AUTH_USER_MODEL, verbose_name='Ответственное лицо'),
        ),
    ]
