# Generated by Django 5.2.7 on 2025-11-03 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        ('warehouses', '0002_alter_warehouse_contact_person'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название типа груза')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('hazard_class', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 - Взрывчатые вещества'), (2, '2 - Газы'), (3, '3 - Легковоспламеняющиеся жидкости'), (4, '4 - Легковоспламеняющиеся твердые вещества'), (5, '5 - Окисляющие вещества'), (6, '6 - Токсичные вещества'), (7, '7 - Радиоактивные материалы'), (8, '8 - Коррозионные вещества'), (9, '9 - Прочие опасные вещества')], null=True, verbose_name='Класс опасности')),
                ('requires_special_handling', models.BooleanField(default=False, verbose_name='Требует особого обращения')),
                ('max_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Макс. температура хранения')),
                ('min_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Мин. температура хранения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Тип груза',
                'verbose_name_plural': 'Типы грузов',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вес (т)')),
                ('volume', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Объем (м³)')),
                ('description', models.TextField(blank=True, verbose_name='Описание груза')),
                ('planned_departure', models.DateTimeField(verbose_name='Плановое время отправления')),
                ('planned_arrival', models.DateTimeField(verbose_name='Плановое время прибытия')),
                ('actual_departure', models.DateTimeField(blank=True, null=True, verbose_name='Фактическое время отправления')),
                ('actual_arrival', models.DateTimeField(blank=True, null=True, verbose_name='Фактическое время прибытия')),
                ('status', models.CharField(choices=[('PLANNED', 'Запланирована'), ('ASSIGNED', 'Назначена'), ('IN_TRANSIT', 'В пути'), ('AT_WAREHOUSE', 'На складе'), ('UNLOADING', 'Разгрузка'), ('COMPLETED', 'Завершена'), ('CANCELLED', 'Отменена'), ('DELAYED', 'Задержана')], default='PLANNED', max_length=20, verbose_name='Статус')),
                ('priority', models.CharField(choices=[('LOW', 'Низкий'), ('MEDIUM', 'Средний'), ('HIGH', 'Высокий'), ('URGENT', 'Срочный')], default='MEDIUM', max_length=10, verbose_name='Приоритет')),
                ('special_instructions', models.TextField(blank=True, verbose_name='Особые указания')),
                ('delay_reason', models.TextField(blank=True, verbose_name='Причина задержки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_shipments', to=settings.AUTH_USER_MODEL, verbose_name='Кем назначена')),
                ('assigned_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.driver', verbose_name='Назначенный водитель')),
                ('assigned_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.vehicle', verbose_name='Назначенный транспорт')),
                ('cargo_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cargo.cargotype', verbose_name='Тип груза')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_shipments', to=settings.AUTH_USER_MODEL, verbose_name='Кем создана')),
                ('destination_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination_shipments', to='warehouses.warehouse', verbose_name='Склад назначения')),
                ('origin_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origin_shipments', to='warehouses.warehouse', verbose_name='Склад отправления')),
            ],
            options={
                'verbose_name': 'Поставка',
                'verbose_name_plural': 'Поставки',
                'ordering': ['-created_at'],
            },
        ),
    ]
