# Generated by Django 5.2.6 on 2025-11-05 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0001_initial'),
        ('vehicles', '0003_alter_vehicle_vehicle_type'),
        ('warehouses', '0002_alter_warehouse_contact_person'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_volume', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Запрашиваемый объем')),
                ('requested_weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Запрашиваемый вес')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает распределения'), ('ASSIGNED', 'Назначена склад'), ('LOADING', 'В процессе загрузки'), ('COMPLETED', 'Завершена'), ('CANCELLED', 'Отменена')], default='PENDING', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Низкий'), ('MEDIUM', 'Средний'), ('HIGH', 'Высокий'), ('URGENT', 'Срочный')], default='MEDIUM', max_length=10)),
                ('arrival_time', models.DateTimeField(verbose_name='Время прибытия')),
                ('expected_start_time', models.DateTimeField(blank=True, null=True, verbose_name='Ожидаемое время начала загрузки')),
                ('actual_start_time', models.DateTimeField(blank=True, null=True, verbose_name='Фактическое время начала загрузки')),
                ('completion_time', models.DateTimeField(blank=True, null=True, verbose_name='Время завершения загрузки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to='warehouses.warehouse', verbose_name='Назначенный склад')),
                ('cargo_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cargo.cargotype', verbose_name='Тип груза')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Создано')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.driver', verbose_name='Водитель')),
                ('requested_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouses.warehouse', verbose_name='Запрашиваемый склад')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle', verbose_name='Транспорт')),
            ],
            options={
                'verbose_name': 'Заявка на загрузку',
                'verbose_name_plural': 'Заявки на загрузку',
                'ordering': ['-arrival_time'],
            },
        ),
    ]
