# Generated by Django 5.2.6 on 2025-11-05 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0002_loadingrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoadingRequest',
        ),
    ]
