# Generated by Django 5.2.7 on 2025-11-03 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=50, unique=True, verbose_name='Номер водительского удостоверения')),
                ('license_category', models.CharField(max_length=10, verbose_name='Категория прав')),
                ('license_expiry', models.DateField(verbose_name='Срок действия прав')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'DRIVER'}, on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Водитель',
                'verbose_name_plural': 'Водители',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20, unique=True, verbose_name='Госномер')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('vehicle_type', models.CharField(choices=[('TRUCK', 'Грузовик'), ('VAN', 'Фургон'), ('TRAILER', 'Прицеп'), ('SPECIAL', 'Спецтранспорт')], max_length=20, verbose_name='Тип транспорта')),
                ('capacity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Грузоподъемность (т)')),
                ('volume', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Объем (м³)')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Доступен'), ('IN_USE', 'В работе'), ('MAINTENANCE', 'На обслуживании'), ('BROKEN', 'Сломан')], default='AVAILABLE', max_length=20, verbose_name='Статус')),
                ('year', models.PositiveIntegerField(verbose_name='Год выпуска')),
                ('vin', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='VIN')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_vehicle', to='vehicles.driver', verbose_name='Текущий водитель')),
            ],
            options={
                'verbose_name': 'Транспортное средство',
                'verbose_name_plural': 'Транспортные средства',
            },
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_drivers', to='vehicles.vehicle', verbose_name='Закрепленное ТС'),
        ),
    ]
