# Generated by Django 5.2.6 on 2025-11-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('Грузовик', 'Грузовик'), ('Фургон', 'Фургон'), ('Прицеп', 'Прицеп'), ('Спецтранспорт', 'Спецтранспорт')], max_length=20, verbose_name='Тип транспорта'),
        ),
    ]
