# Generated by Django 5.2.6 on 2025-11-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_vehicle_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('TRUCK', 'Грузовик'), ('VAN', 'Фургон'), ('TRAILER', 'Прицеп'), ('SPECIAL', 'Спецтранспорт')], max_length=20, verbose_name='Тип транспорта'),
        ),
    ]
