# Generated by Django 5.2.6 on 2025-11-06 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_alter_vehicle_vehicle_type'),
        ('warehouses', '0002_alter_warehouse_contact_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='current_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouses.warehouse', verbose_name='Текущий склад'),
        ),
    ]
