# Generated by Django 5.1 on 2025-11-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_vehicle_current_warehouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='current_driver',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vin',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='year',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='cargo_description',
            field=models.TextField(blank=True, verbose_name='Описание груза'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='cargo_recipient',
            field=models.CharField(blank=True, max_length=200, verbose_name='Грузополучатель'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='cargo_volume',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Объем ТМЦ'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='capacity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Грузоподъемность (т)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('TRUCK', 'Грузовик'), ('VAN', 'Фургон'), ('TRAILER', 'Прицеп'), ('SPECIAL', 'Спецтранспорт')], default='TRUCK', max_length=20, verbose_name='Тип транспорта'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Объем (м³)'),
        ),
    ]
